In [33]:
#1
import numpy
arr = numpy.array([1,2,3,4,5,6,7,8,9,10])

print(arr)

#Mean
print(f"Mean of the array is: {arr.mean()}")

# Maximum
print(f"Maximum of array is {arr.max()}")

#Minimum
print(f"Minimum of array is {arr.min()}")

[ 1  2  3  4  5  6  7  8  9 10]
Mean of the array is: 5.5
Maximum of array is 10
Minimum of array is 1


In [32]:
#2
import numpy as np
arr = np.array([10,20,30,40,50])

#1 Accessing Third element
print(f"Third Element in the array is : {arr[3]}")

#get the first three elements
print(f"first three elements in the array is : {arr[:3]}")

#replace 30 with 35
arr[2]= 35
print(arr)

Third Element in the array is : 40
first three elements in the array is : [10 20 30]
[10 20 35 40 50]


In [34]:
#3
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr= arr.reshape(3,3)
print(newarr)
#shape of array
print(f"shape of the array is : {newarr.shape}")

#sum of all elements
total=0
for x in np.nditer(newarr):
    total= total+x
print(f"Sum of elements is : {total}")

#sum of each row
for i, row in enumerate(newarr):
    print(f"sum of {i+1}th row is: {np.sum(row)}")
    

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of the array is : (3, 3)
Sum of elements is : 45
sum of 1th row is: 6
sum of 2th row is: 15
sum of 3th row is: 24


In [5]:
#4
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

#elemnt 5
print(arr[1,1])

#last column
x= arr[:,2]
print(f" Lasst column : {x}")
#second row
y= arr[1,:]
print(f"second row : {y}")

5
 Lasst column : [3 6 9]
second row : [4 5 6]
